### PR TITLE
Add CodeSignature to MalwarebytesAntiMalware

### PR DESCRIPTION
**Pull request by erikng**
I had to add an unarchiver, but it's after the initial check phase, so it shouldn't impact people anyone using the download/pkg/install version. This is also working with [Alan's munki recipe](https://github.com/autopkg/aysiu-recipes/tree/master/MalwarebytesAntiMalware)

Going to ping @aysiu as well to if he wants to change any parts of his recipe.

### CODE REVIEW

**Comment by aysiu** [comment]
Thanks for pinging me, @erikng. I'm not a super AutoPkg recipe expert. Would I just pop this into my recipe (I'll test it afterwards, of course)?
```        <dict>
         <key>Processor</key>
          <string>CodeSignatureVerifier</string>
          <key>Arguments</key>
          <dict>
            <key>input_path</key>
            <string>%RECIPE_CACHE_DIR%/%NAME%/Malwarebytes Anti-Malware.app</string>
            <key>requirement</key>
            <string>identifier "com.malwarebytes.antimalware" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "GVZRY6KDKR"</string>
          </dict>
        </dict>```

**Comment by erikng** [comment]
Well actually you don't need to do anything to your recipe. As it stands it's currently working (I tested it) and using code signature verification. If you'd like, you can simply drop your unarchiving step. You don't have to, but it would reduce cpu cycles/steps.

**Comment by erikng** [comment]
One other thought - Rich needs to approve this prior to making your change or your recipe will break.

**Comment by aysiu** [comment]
So leave it for now?

**Comment by erikng** [comment]
Yeah, let's see what Rich says (although I don't think he will not merge this).

**Comment by rtrouton** [comment]
Looks good to me. Merging.

**Comment by aysiu** [comment]
Thanks!

**Pull request merged**
